# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb23000786da5e6e4b38ad655d6e7d8a59fc0881111d52134dde907214637deb720654ecdb6cb7bf8ae402d07c03c0f1cf0de326dc2a12a8597dda36cb3c1385

test:
  secret_key_base: 4c0cc3d9fc8b7c5af55143a5ad82f702d887a1a6225054b36bc9432fc8fa141311eac46dc0847da3e445916feb09e9aa23b319a142fdc33e8068fc3de3853988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
